//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyControl.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyControl.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 上午 的本地化字符串。
        /// </summary>
        public static string Am {
            get {
                return ResourceManager.GetString("Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法自注册复合命令 的本地化字符串。
        /// </summary>
        public static string CannotRegisterCompositeCommandInItself {
            get {
                return ResourceManager.GetString("CannotRegisterCompositeCommandInItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能注册同一命令两次 的本地化字符串。
        /// </summary>
        public static string CannotRegisterSameCommandTwice {
            get {
                return ResourceManager.GetString("CannotRegisterSameCommandTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有 的本地化字符串。
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭其他 的本地化字符串。
        /// </summary>
        public static string CloseOther {
            get {
                return ResourceManager.GetString("CloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的图片路径 的本地化字符串。
        /// </summary>
        public static string ErrorImgPath {
            get {
                return ResourceManager.GetString("ErrorImgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的图片尺寸 的本地化字符串。
        /// </summary>
        public static string ErrorImgSize {
            get {
                return ResourceManager.GetString("ErrorImgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找 的本地化字符串。
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误 的本地化字符串。
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔10分钟 的本地化字符串。
        /// </summary>
        public static string Interval10m {
            get {
                return ResourceManager.GetString("Interval10m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔1小时 的本地化字符串。
        /// </summary>
        public static string Interval1h {
            get {
                return ResourceManager.GetString("Interval1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔1分钟 的本地化字符串。
        /// </summary>
        public static string Interval1m {
            get {
                return ResourceManager.GetString("Interval1m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔2小时 的本地化字符串。
        /// </summary>
        public static string Interval2h {
            get {
                return ResourceManager.GetString("Interval2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔30分钟 的本地化字符串。
        /// </summary>
        public static string Interval30m {
            get {
                return ResourceManager.GetString("Interval30m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔30秒 的本地化字符串。
        /// </summary>
        public static string Interval30s {
            get {
                return ResourceManager.GetString("Interval30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔5分钟 的本地化字符串。
        /// </summary>
        public static string Interval5m {
            get {
                return ResourceManager.GetString("Interval5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空 的本地化字符串。
        /// </summary>
        public static string IsNecessary {
            get {
                return ResourceManager.GetString("IsNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转 的本地化字符串。
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找类似 {0} 的本地化字符串。 的本地化字符串。
        /// </summary>
        public static string LangComment {
            get {
                return ResourceManager.GetString("LangComment", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 杂项 的本地化字符串。
        /// </summary>
        public static string Miscellaneous
        {
            get
            {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不在范围内 的本地化字符串。
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面模式 的本地化字符串。
        /// </summary>
        public static string PageMode {
            get {
                return ResourceManager.GetString("PageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下午 的本地化字符串。
        /// </summary>
        public static string Pm {
            get {
                return ResourceManager.GetString("Pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG图片 的本地化字符串。
        /// </summary>
        public static string PngImg {
            get {
                return ResourceManager.GetString("PngImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动模式 的本地化字符串。
        /// </summary>
        public static string ScrollMode {
            get {
                return ResourceManager.GetString("ScrollMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过大 的本地化字符串。
        /// </summary>
        public static string TooLarge {
            get {
                return ResourceManager.GetString("TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双页模式 的本地化字符串。
        /// </summary>
        public static string TwoPageMode {
            get {
                return ResourceManager.GetString("TwoPageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知大小 的本地化字符串。
        /// </summary>
        public static string UnknownSize {
            get {
                return ResourceManager.GetString("UnknownSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
