//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyControlDemo.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyControlDemo.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimationPath.
        /// </summary>
        public static string AnimationPath {
            get {
                return ResourceManager.GetString("AnimationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tray icon is open and will hide the window instead of closing the program.
        /// </summary>
        public static string AppClosingTip {
            get {
                return ResourceManager.GetString("AppClosingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the basic information.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic layout.
        /// </summary>
        public static string BasicLayout {
            get {
                return ResourceManager.GetString("BasicLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink.
        /// </summary>
        public static string Blink {
            get {
                return ResourceManager.GetString("Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        public static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom button.
        /// </summary>
        public static string ButtonCustom {
            get {
                return ResourceManager.GetString("ButtonCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonGroup.
        /// </summary>
        public static string ButtonGroup {
            get {
                return ResourceManager.GetString("ButtonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarWithClock.
        /// </summary>
        public static string CalendarWithClock {
            get {
                return ResourceManager.GetString("CalendarWithClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel.
        /// </summary>
        public static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to restart to change the language?.
        /// </summary>
        public static string ChangeLangAsk {
            get {
                return ResourceManager.GetString("ChangeLangAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatBubble.
        /// </summary>
        public static string ChatBubble {
            get {
                return ResourceManager.GetString("ChatBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatroom.
        /// </summary>
        public static string Chatroom {
            get {
                return ResourceManager.GetString("Chatroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckComboBox.
        /// </summary>
        public static string CheckComboBox {
            get {
                return ResourceManager.GetString("CheckComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CirclePanel.
        /// </summary>
        public static string CirclePanel {
            get {
                return ResourceManager.GetString("CirclePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to count.
        /// </summary>
        public static string Click2Count {
            get {
                return ResourceManager.GetString("Click2Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker.
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column offset.
        /// </summary>
        public static string ColumnOffset {
            get {
                return ResourceManager.GetString("ColumnOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column spacing.
        /// </summary>
        public static string ColumnSpacing {
            get {
                return ResourceManager.GetString("ColumnSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox.
        /// </summary>
        public static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareSlider.
        /// </summary>
        public static string CompareSlider {
            get {
                return ResourceManager.GetString("CompareSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the content.
        /// </summary>
        public static string ContentDemoStr {
            get {
                return ResourceManager.GetString("ContentDemoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoverFlow.
        /// </summary>
        public static string CoverFlow {
            get {
                return ResourceManager.GetString("CoverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoverView.
        /// </summary>
        public static string CoverView {
            get {
                return ResourceManager.GetString("CoverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        public static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string DataGrid {
            get {
                return ResourceManager.GetString("DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatePicker.
        /// </summary>
        public static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimePicker.
        /// </summary>
        public static string DateTimePicker {
            get {
                return ResourceManager.GetString("DateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog.
        /// </summary>
        public static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog demo.
        /// </summary>
        public static string DialogDemo {
            get {
                return ResourceManager.GetString("DialogDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider.
        /// </summary>
        public static string Divider {
            get {
                return ResourceManager.GetString("Divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese document.
        /// </summary>
        public static string Doc_cn {
            get {
                return ResourceManager.GetString("Doc_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English document.
        /// </summary>
        public static string Doc_en {
            get {
                return ResourceManager.GetString("Doc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag here.
        /// </summary>
        public static string DragHere {
            get {
                return ResourceManager.GetString("DragHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer.
        /// </summary>
        public static string Drawer {
            get {
                return ResourceManager.GetString("Drawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expander.
        /// </summary>
        public static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexPanel.
        /// </summary>
        public static string FlexPanel {
            get {
                return ResourceManager.GetString("FlexPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlipClock.
        /// </summary>
        public static string FlipClock {
            get {
                return ResourceManager.GetString("FlipClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloatingBlock.
        /// </summary>
        public static string FloatingBlock {
            get {
                return ResourceManager.GetString("FloatingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowDocument.
        /// </summary>
        public static string FlowDocument {
            get {
                return ResourceManager.GetString("FlowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowDocumentPageViewer.
        /// </summary>
        public static string FlowDocumentPageViewer {
            get {
                return ResourceManager.GetString("FlowDocumentPageViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowDocumentReader.
        /// </summary>
        public static string FlowDocumentReader {
            get {
                return ResourceManager.GetString("FlowDocumentReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowDocumentScrollViewer.
        /// </summary>
        public static string FlowDocumentScrollViewer {
            get {
                return ResourceManager.GetString("FlowDocumentScrollViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        public static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GifImage.
        /// </summary>
        public static string GifImage {
            get {
                return ResourceManager.GetString("GifImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GotoTop.
        /// </summary>
        public static string GotoTop {
            get {
                return ResourceManager.GetString("GotoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravatar.
        /// </summary>
        public static string Gravatar {
            get {
                return ResourceManager.GetString("Gravatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBox.
        /// </summary>
        public static string GroupBox {
            get {
                return ResourceManager.GetString("GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl.
        /// </summary>
        public static string Growl {
            get {
                return ResourceManager.GetString("Growl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been detected!Do you want to update?.
        /// </summary>
        public static string GrowlAsk {
            get {
                return ResourceManager.GetString("GrowlAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl demo.
        /// </summary>
        public static string GrowlDemo {
            get {
                return ResourceManager.GetString("GrowlDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed. please check your network!.
        /// </summary>
        public static string GrowlError {
            get {
                return ResourceManager.GetString("GrowlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has crashed~~~.
        /// </summary>
        public static string GrowlFatal {
            get {
                return ResourceManager.GetString("GrowlFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a nice day today~~~.
        /// </summary>
        public static string GrowlInfo {
            get {
                return ResourceManager.GetString("GrowlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully!.
        /// </summary>
        public static string GrowlSuccess {
            get {
                return ResourceManager.GetString("GrowlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space is running out!.
        /// </summary>
        public static string GrowlWarning {
            get {
                return ResourceManager.GetString("GrowlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HatchBrushGenerator.
        /// </summary>
        public static string HatchBrushGenerator {
            get {
                return ResourceManager.GetString("HatchBrushGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoneycombPanel.
        /// </summary>
        public static string HoneycombPanel {
            get {
                return ResourceManager.GetString("HoneycombPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid layout.
        /// </summary>
        public static string HybridLayout {
            get {
                return ResourceManager.GetString("HybridLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageBlock.
        /// </summary>
        public static string ImageBlock {
            get {
                return ResourceManager.GetString("ImageBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageBrowser.
        /// </summary>
        public static string ImageBrowser {
            get {
                return ResourceManager.GetString("ImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageSelector.
        /// </summary>
        public static string ImageSelector {
            get {
                return ResourceManager.GetString("ImageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Dialog.
        /// </summary>
        public static string InteractiveDialog {
            get {
                return ResourceManager.GetString("InteractiveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not a phone number.
        /// </summary>
        public static string IsNotPhone {
            get {
                return ResourceManager.GetString("IsNotPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks up a localized string similar to &quot;{0}&quot;..
        /// </summary>
        public static string LangComment {
            get {
                return ResourceManager.GetString("LangComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListBox.
        /// </summary>
        public static string ListBox {
            get {
                return ResourceManager.GetString("ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView.
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier.
        /// </summary>
        public static string Magnifier {
            get {
                return ResourceManager.GetString("Magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox.
        /// </summary>
        public static string MessageBox {
            get {
                return ResourceManager.GetString("MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphing Animation.
        /// </summary>
        public static string Morphing_Animation {
            get {
                return ResourceManager.GetString("Morphing Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New window.
        /// </summary>
        public static string NewWindow {
            get {
                return ResourceManager.GetString("NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifyIcon.
        /// </summary>
        public static string NotifyIcon {
            get {
                return ResourceManager.GetString("NotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericUpDown.
        /// </summary>
        public static string NumericUpDown {
            get {
                return ResourceManager.GetString("NumericUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open blur window.
        /// </summary>
        public static string OpenBlurWindow {
            get {
                return ResourceManager.GetString("OpenBlurWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open common window.
        /// </summary>
        public static string OpenCommonWindow {
            get {
                return ResourceManager.GetString("OpenCommonWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open custom content window.
        /// </summary>
        public static string OpenCustomContentWindow {
            get {
                return ResourceManager.GetString("OpenCustomContentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open custom message window.
        /// </summary>
        public static string OpenCustomMessageWindow {
            get {
                return ResourceManager.GetString("OpenCustomMessageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open custom Non-client Area window.
        /// </summary>
        public static string OpenCustomNonClientAreaWindow {
            get {
                return ResourceManager.GetString("OpenCustomNonClientAreaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open glowWindow.
        /// </summary>
        public static string OpenGlowWindow {
            get {
                return ResourceManager.GetString("OpenGlowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open image browser.
        /// </summary>
        public static string OpenImageBrowser {
            get {
                return ResourceManager.GetString("OpenImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open message window.
        /// </summary>
        public static string OpenMessageWindow {
            get {
                return ResourceManager.GetString("OpenMessageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open mouse follow window.
        /// </summary>
        public static string OpenMouseFollowWindow {
            get {
                return ResourceManager.GetString("OpenMouseFollowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open native common window.
        /// </summary>
        public static string OpenNativeCommonWindow {
            get {
                return ResourceManager.GetString("OpenNativeCommonWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open navigation window.
        /// </summary>
        public static string OpenNavigationWindow {
            get {
                return ResourceManager.GetString("OpenNavigationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open no Non-client Area dragable window.
        /// </summary>
        public static string OpenNoNonClientAreaDragableWindow {
            get {
                return ResourceManager.GetString("OpenNoNonClientAreaDragableWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Panel.
        /// </summary>
        public static string OpenPanel {
            get {
                return ResourceManager.GetString("OpenPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sprite.
        /// </summary>
        public static string OpenSprite {
            get {
                return ResourceManager.GetString("OpenSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutlineText.
        /// </summary>
        public static string OutlineText {
            get {
                return ResourceManager.GetString("OutlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagination.
        /// </summary>
        public static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBox.
        /// </summary>
        public static string PasswordBox {
            get {
                return ResourceManager.GetString("PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinBox.
        /// </summary>
        public static string PinBox {
            get {
                return ResourceManager.GetString("PinBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input....
        /// </summary>
        public static string PleaseInput {
            get {
                return ResourceManager.GetString("PleaseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter content.
        /// </summary>
        public static string PlsEnterContent {
            get {
                return ResourceManager.GetString("PlsEnterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter email.
        /// </summary>
        public static string PlsEnterEmail {
            get {
                return ResourceManager.GetString("PlsEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a keyword.
        /// </summary>
        public static string PlsEnterKey {
            get {
                return ResourceManager.GetString("PlsEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poptip.
        /// </summary>
        public static string Poptip {
            get {
                return ResourceManager.GetString("Poptip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top-start;top;top-end;right-start;right;right-end;bottom-end;bottom;bottom-start;left-end;left;left-start.
        /// </summary>
        public static string PoptipPositionStr {
            get {
                return ResourceManager.GetString("PoptipPositionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical demos.
        /// </summary>
        public static string PracticalDemos {
            get {
                return ResourceManager.GetString("PracticalDemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviewSlider.
        /// </summary>
        public static string PreviewSlider {
            get {
                return ResourceManager.GetString("PreviewSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressBar.
        /// </summary>
        public static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressButton.
        /// </summary>
        public static string ProgressButton {
            get {
                return ResourceManager.GetString("ProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyGrid.
        /// </summary>
        public static string PropertyGrid {
            get {
                return ResourceManager.GetString("PropertyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to talk.
        /// </summary>
        public static string PushToTalk {
            get {
                return ResourceManager.GetString("PushToTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ Group.
        /// </summary>
        public static string QQGroup {
            get {
                return ResourceManager.GetString("QQGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioButton.
        /// </summary>
        public static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangeSlider.
        /// </summary>
        public static string RangeSlider {
            get {
                return ResourceManager.GetString("RangeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation.
        /// </summary>
        public static string Recommendation {
            get {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelativePanel.
        /// </summary>
        public static string RelativePanel {
            get {
                return ResourceManager.GetString("RelativePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an item.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepeatButton.
        /// </summary>
        public static string RepeatButton {
            get {
                return ResourceManager.GetString("RepeatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive layout.
        /// </summary>
        public static string ResponsiveLayout {
            get {
                return ResourceManager.GetString("ResponsiveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichTextBox.
        /// </summary>
        public static string RichTextBox {
            get {
                return ResourceManager.GetString("RichTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click here.
        /// </summary>
        public static string RightClickHere {
            get {
                return ResourceManager.GetString("RightClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunningBlock.
        /// </summary>
        public static string RunningBlock {
            get {
                return ResourceManager.GetString("RunningBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrollViewer.
        /// </summary>
        public static string ScrollViewer {
            get {
                return ResourceManager.GetString("ScrollViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchBar.
        /// </summary>
        public static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification.
        /// </summary>
        public static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in the current window.
        /// </summary>
        public static string ShowInCurrentWindow {
            get {
                return ResourceManager.GetString("ShowInCurrentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in the main window.
        /// </summary>
        public static string ShowInMainWindow {
            get {
                return ResourceManager.GetString("ShowInMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowRowNumber.
        /// </summary>
        public static string ShowRowNumber {
            get {
                return ResourceManager.GetString("ShowRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SideMenu.
        /// </summary>
        public static string SideMenu {
            get {
                return ResourceManager.GetString("SideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplitButton.
        /// </summary>
        public static string SplitButton {
            get {
                return ResourceManager.GetString("SplitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite.
        /// </summary>
        public static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start screenshot.
        /// </summary>
        public static string StartScreenshot {
            get {
                return ResourceManager.GetString("StartScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stays open.
        /// </summary>
        public static string StaysOpen {
            get {
                return ResourceManager.GetString("StaysOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepBar.
        /// </summary>
        public static string StepBar {
            get {
                return ResourceManager.GetString("StepBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabControl.
        /// </summary>
        public static string TabControl {
            get {
                return ResourceManager.GetString("TabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlock.
        /// </summary>
        public static string TextBlock {
            get {
                return ResourceManager.GetString("TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextDialog.
        /// </summary>
        public static string TextDialog {
            get {
                return ResourceManager.GetString("TextDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextDialog(In control).
        /// </summary>
        public static string TextDialogInControl {
            get {
                return ResourceManager.GetString("TextDialogInControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextDialog with timer.
        /// </summary>
        public static string TextDialogWithTimer {
            get {
                return ResourceManager.GetString("TextDialogWithTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeBar.
        /// </summary>
        public static string TimeBar {
            get {
                return ResourceManager.GetString("TimeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimePicker.
        /// </summary>
        public static string TimePicker {
            get {
                return ResourceManager.GetString("TimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the title.
        /// </summary>
        public static string TitleDemoStr1 {
            get {
                return ResourceManager.GetString("TitleDemoStr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be filled in.
        /// </summary>
        public static string TitleDemoStr2 {
            get {
                return ResourceManager.GetString("TitleDemoStr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is on the left.
        /// </summary>
        public static string TitleDemoStr3 {
            get {
                return ResourceManager.GetString("TitleDemoStr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleButton.
        /// </summary>
        public static string ToggleButton {
            get {
                return ResourceManager.GetString("ToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolBar.
        /// </summary>
        public static string ToolBar {
            get {
                return ResourceManager.GetString("ToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransitioningContentControl.
        /// </summary>
        public static string TransitioningContentControl {
            get {
                return ResourceManager.GetString("TransitioningContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeView.
        /// </summary>
        public static string TreeView {
            get {
                return ResourceManager.GetString("TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to close app?.
        /// </summary>
        public static string Try2CloseApp {
            get {
                return ResourceManager.GetString("Try2CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload;Uploading.
        /// </summary>
        public static string UploadStr {
            get {
                return ResourceManager.GetString("UploadStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsix.
        /// </summary>
        public static string Vsix {
            get {
                return ResourceManager.GetString("Vsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterfallPanel.
        /// </summary>
        public static string WaterfallPanel {
            get {
                return ResourceManager.GetString("WaterfallPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
