//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyControl.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyControl.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的图片路径！ 的本地化字符串。
        /// </summary>
        public static string ErrorImgPath {
            get {
                return ResourceManager.GetString("ErrorImgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的图片尺寸！ 的本地化字符串。
        /// </summary>
        public static string ErrorImgSize {
            get {
                return ResourceManager.GetString("ErrorImgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔10分钟 的本地化字符串。
        /// </summary>
        public static string Interval10m {
            get {
                return ResourceManager.GetString("Interval10m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔1小时 的本地化字符串。
        /// </summary>
        public static string Interval1h {
            get {
                return ResourceManager.GetString("Interval1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔1分钟 的本地化字符串。
        /// </summary>
        public static string Interval1m {
            get {
                return ResourceManager.GetString("Interval1m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔2小时 的本地化字符串。
        /// </summary>
        public static string Interval2h {
            get {
                return ResourceManager.GetString("Interval2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔30分钟 的本地化字符串。
        /// </summary>
        public static string Interval30m {
            get {
                return ResourceManager.GetString("Interval30m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔30秒 的本地化字符串。
        /// </summary>
        public static string Interval30s {
            get {
                return ResourceManager.GetString("Interval30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔5分钟 的本地化字符串。
        /// </summary>
        public static string Interval5m {
            get {
                return ResourceManager.GetString("Interval5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG图片 的本地化字符串。
        /// </summary>
        public static string PngImg {
            get {
                return ResourceManager.GetString("PngImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过大 的本地化字符串。
        /// </summary>
        public static string TooLarge {
            get {
                return ResourceManager.GetString("TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知大小 的本地化字符串。
        /// </summary>
        public static string UnknownSize {
            get {
                return ResourceManager.GetString("UnknownSize", resourceCulture);
            }
        }
    }
}
