namespace Standard
{
    using System;

    internal enum OLECMDID
    {
        ALLOWUILESSSAVEAS = 0x2e,
        CLEARSELECTION = 0x12,
        CLOSE = 0x2d,
        COPY = 12,
        CUT = 11,
        DELETE = 0x21,
        DONTDOWNLOADCSS = 0x2f,
        ENABLE_INTERACTION = 0x24,
        FIND = 0x20,
        FOCUSVIEWCONTROLS = 0x39,
        FOCUSVIEWCONTROLSQUERY = 0x3a,
        GETPRINTTEMPLATE = 0x34,
        GETZOOMRANGE = 20,
        HIDETOOLBARS = 0x18,
        HTTPEQUIV = 0x22,
        HTTPEQUIV_DONE = 0x23,
        NEW = 2,
        ONTOOLBARACTIVATED = 0x1f,
        ONUNLOAD = 0x25,
        OPEN = 1,
        PAGEACTIONBLOCKED = 0x37,
        PAGEACTIONUIQUERY = 0x38,
        PAGESETUP = 8,
        PASTE = 13,
        PASTESPECIAL = 14,
        PREREFRESH = 0x27,
        PRINT = 6,
        PRINT2 = 0x31,
        PRINTPREVIEW = 7,
        PRINTPREVIEW2 = 50,
        PROPERTIES = 10,
        PROPERTYBAG2 = 0x26,
        REDO = 0x10,
        REFRESH = 0x16,
        SAVE = 3,
        SAVEAS = 4,
        SAVECOPYAS = 5,
        SELECTALL = 0x11,
        SETDOWNLOADSTATE = 0x1d,
        SETPRINTTEMPLATE = 0x33,
        SETPROGRESSMAX = 0x19,
        SETPROGRESSPOS = 0x1a,
        SETPROGRESSTEXT = 0x1b,
        SETTITLE = 0x1c,
        SHOWFIND = 0x2a,
        SHOWMESSAGE = 0x29,
        SHOWPAGEACTIONMENU = 0x3b,
        SHOWPAGESETUP = 0x2b,
        SHOWPRINT = 0x2c,
        SHOWSCRIPTERROR = 40,
        SPELL = 9,
        STOP = 0x17,
        STOPDOWNLOAD = 30,
        UNDO = 15,
        UPDATECOMMANDS = 0x15,
        UPDATEPAGESTATUS = 0x30,
        ZOOM = 0x13
    }
}

