//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyControlDemo.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyControlDemo.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 动画路径 的本地化字符串。
        /// </summary>
        public static string AnimationPath {
            get {
                return ResourceManager.GetString("AnimationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明按钮 的本地化字符串。
        /// </summary>
        public static string ButtonOpacity {
            get {
                return ResourceManager.GetString("ButtonOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮播 的本地化字符串。
        /// </summary>
        public static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复选框 的本地化字符串。
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色拾取器 的本地化字符串。
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比滑块 的本地化字符串。
        /// </summary>
        public static string CompareSlider {
            get {
                return ResourceManager.GetString("CompareSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件 的本地化字符串。
        /// </summary>
        public static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险 的本地化字符串。
        /// </summary>
        public static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开框 的本地化字符串。
        /// </summary>
        public static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息通知 的本地化字符串。
        /// </summary>
        public static string Growl {
            get {
                return ResourceManager.GetString("Growl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到有新版本！ 的本地化字符串。
        /// </summary>
        public static string GrowlAsk {
            get {
                return ResourceManager.GetString("GrowlAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败，请检查网络！ 的本地化字符串。
        /// </summary>
        public static string GrowlError {
            get {
                return ResourceManager.GetString("GrowlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已崩溃~~~ 的本地化字符串。
        /// </summary>
        public static string GrowlFatal {
            get {
                return ResourceManager.GetString("GrowlFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天的天气不错~~~ 的本地化字符串。
        /// </summary>
        public static string GrowlInfo {
            get {
                return ResourceManager.GetString("GrowlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存成功！ 的本地化字符串。
        /// </summary>
        public static string GrowlSuccess {
            get {
                return ResourceManager.GetString("GrowlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘空间快要满了！ 的本地化字符串。
        /// </summary>
        public static string GrowlWarning {
            get {
                return ResourceManager.GetString("GrowlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片浏览器 的本地化字符串。
        /// </summary>
        public static string ImageBrowser {
            get {
                return ResourceManager.GetString("ImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载条 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开图片浏览器 的本地化字符串。
        /// </summary>
        public static string OpenImageBrowser {
            get {
                return ResourceManager.GetString("OpenImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页码条 的本地化字符串。
        /// </summary>
        public static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要 的本地化字符串。
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度条 的本地化字符串。
        /// </summary>
        public static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式模板 的本地化字符串。
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项卡控件 的本地化字符串。
        /// </summary>
        public static string TabControl {
            get {
                return ResourceManager.GetString("TabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本块 的本地化字符串。
        /// </summary>
        public static string TextBlock {
            get {
                return ResourceManager.GetString("TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间条 的本地化字符串。
        /// </summary>
        public static string TimeBar {
            get {
                return ResourceManager.GetString("TimeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换按钮 的本地化字符串。
        /// </summary>
        public static string ToggleButton {
            get {
                return ResourceManager.GetString("ToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
