//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyControlDemo.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyControlDemo.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动画路径 的本地化字符串。
        /// </summary>
        public static string AnimationPath {
            get {
                return ResourceManager.GetString("AnimationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 的本地化字符串。
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写基本信息 的本地化字符串。
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 博客 的本地化字符串。
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框 的本地化字符串。
        /// </summary>
        public static string Border1 {
            get {
                return ResourceManager.GetString("Border1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画刷 的本地化字符串。
        /// </summary>
        public static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明按钮 的本地化字符串。
        /// </summary>
        public static string ButtonOpacity {
            get {
                return ResourceManager.GetString("ButtonOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日历 的本地化字符串。
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带时钟的日历 的本地化字符串。
        /// </summary>
        public static string CalendarWithClock {
            get {
                return ResourceManager.GetString("CalendarWithClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮播 的本地化字符串。
        /// </summary>
        public static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否重启以更改语言？ 的本地化字符串。
        /// </summary>
        public static string ChangeLangAsk {
            get {
                return ResourceManager.GetString("ChangeLangAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讨论室 的本地化字符串。
        /// </summary>
        public static string Chatroom {
            get {
                return ResourceManager.GetString("Chatroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复选框 的本地化字符串。
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆形布局 的本地化字符串。
        /// </summary>
        public static string CirclePanel {
            get {
                return ResourceManager.GetString("CirclePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆形进度条 的本地化字符串。
        /// </summary>
        public static string CircleProgressBar {
            get {
                return ResourceManager.GetString("CircleProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟 的本地化字符串。
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色拾取器 的本地化字符串。
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合框 的本地化字符串。
        /// </summary>
        public static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比滑块 的本地化字符串。
        /// </summary>
        public static string CompareSlider {
            get {
                return ResourceManager.GetString("CompareSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是内容 的本地化字符串。
        /// </summary>
        public static string ContentDemoStr {
            get {
                return ResourceManager.GetString("ContentDemoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贡献者 的本地化字符串。
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件 的本地化字符串。
        /// </summary>
        public static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面流 的本地化字符串。
        /// </summary>
        public static string CoverFlow {
            get {
                return ResourceManager.GetString("CoverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面视图 的本地化字符串。
        /// </summary>
        public static string CoverView {
            get {
                return ResourceManager.GetString("CoverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险 的本地化字符串。
        /// </summary>
        public static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表格 的本地化字符串。
        /// </summary>
        public static string DataGrid {
            get {
                return ResourceManager.GetString("DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期选择器 的本地化字符串。
        /// </summary>
        public static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期时间选择器 的本地化字符串。
        /// </summary>
        public static string DateTimePicker {
            get {
                return ResourceManager.GetString("DateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这里拖拽 的本地化字符串。
        /// </summary>
        public static string DragHere {
            get {
                return ResourceManager.GetString("DragHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开框 的本地化字符串。
        /// </summary>
        public static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 严重 的本地化字符串。
        /// </summary>
        public static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻页时钟 的本地化字符串。
        /// </summary>
        public static string FlipClock {
            get {
                return ResourceManager.GetString("FlipClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gif图片 的本地化字符串。
        /// </summary>
        public static string GifImage {
            get {
                return ResourceManager.GetString("GifImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组框 的本地化字符串。
        /// </summary>
        public static string GroupBox {
            get {
                return ResourceManager.GetString("GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组数 的本地化字符串。
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息通知 的本地化字符串。
        /// </summary>
        public static string Growl {
            get {
                return ResourceManager.GetString("Growl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到有新版本！是否更新？ 的本地化字符串。
        /// </summary>
        public static string GrowlAsk {
            get {
                return ResourceManager.GetString("GrowlAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败，请检查网络！ 的本地化字符串。
        /// </summary>
        public static string GrowlError {
            get {
                return ResourceManager.GetString("GrowlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已崩溃~~~ 的本地化字符串。
        /// </summary>
        public static string GrowlFatal {
            get {
                return ResourceManager.GetString("GrowlFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天的天气不错~~~ 的本地化字符串。
        /// </summary>
        public static string GrowlInfo {
            get {
                return ResourceManager.GetString("GrowlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存成功！ 的本地化字符串。
        /// </summary>
        public static string GrowlSuccess {
            get {
                return ResourceManager.GetString("GrowlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘空间快要满了！ 的本地化字符串。
        /// </summary>
        public static string GrowlWarning {
            get {
                return ResourceManager.GetString("GrowlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片浏览器 的本地化字符串。
        /// </summary>
        public static string ImageBrowser {
            get {
                return ResourceManager.GetString("ImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索引 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是手机号码 的本地化字符串。
        /// </summary>
        public static string IsNotPhone {
            get {
                return ResourceManager.GetString("IsNotPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表框 的本地化字符串。
        /// </summary>
        public static string ListBox {
            get {
                return ResourceManager.GetString("ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表视图 的本地化字符串。
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载条 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值选择控件 的本地化字符串。
        /// </summary>
        public static string NumericUpDown {
            get {
                return ResourceManager.GetString("NumericUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开背景模糊窗口 的本地化字符串。
        /// </summary>
        public static string OpenBlurWindow {
            get {
                return ResourceManager.GetString("OpenBlurWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开常规窗口 的本地化字符串。
        /// </summary>
        public static string OpenCommonWindow {
            get {
                return ResourceManager.GetString("OpenCommonWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开自定义内容窗口 的本地化字符串。
        /// </summary>
        public static string OpenCustomContentWindow {
            get {
                return ResourceManager.GetString("OpenCustomContentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开自定义非客户端区域窗口 的本地化字符串。
        /// </summary>
        public static string OpenCustomNonClientAreaWindow {
            get {
                return ResourceManager.GetString("OpenCustomNonClientAreaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开图片浏览器 的本地化字符串。
        /// </summary>
        public static string OpenImageBrowser {
            get {
                return ResourceManager.GetString("OpenImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开消息窗口 的本地化字符串。
        /// </summary>
        public static string OpenMessageWindow {
            get {
                return ResourceManager.GetString("OpenMessageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开鼠标跟随窗口 的本地化字符串。
        /// </summary>
        public static string OpenMouseFollowWindow {
            get {
                return ResourceManager.GetString("OpenMouseFollowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开无非客户端区域可拖拽窗口 的本地化字符串。
        /// </summary>
        public static string OpenNoNonClientAreaDragableWindow {
            get {
                return ResourceManager.GetString("OpenNoNonClientAreaDragableWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮廓文本 的本地化字符串。
        /// </summary>
        public static string OutlineText {
            get {
                return ResourceManager.GetString("OutlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页码条 的本地化字符串。
        /// </summary>
        public static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码框 的本地化字符串。
        /// </summary>
        public static string PasswordBox {
            get {
                return ResourceManager.GetString("PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入内容 的本地化字符串。
        /// </summary>
        public static string PlsEnterContent {
            get {
                return ResourceManager.GetString("PlsEnterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入邮箱 的本地化字符串。
        /// </summary>
        public static string PlsEnterEmail {
            get {
                return ResourceManager.GetString("PlsEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览滑块 的本地化字符串。
        /// </summary>
        public static string PreviewSlider {
            get {
                return ResourceManager.GetString("PreviewSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要 的本地化字符串。
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度条 的本地化字符串。
        /// </summary>
        public static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ群 的本地化字符串。
        /// </summary>
        public static string QQGroup {
            get {
                return ResourceManager.GetString("QQGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选按钮 的本地化字符串。
        /// </summary>
        public static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评分 的本地化字符串。
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码仓库 的本地化字符串。
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 富文本框 的本地化字符串。
        /// </summary>
        public static string RichTextBox {
            get {
                return ResourceManager.GetString("RichTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这里右击 的本地化字符串。
        /// </summary>
        public static string RightClickHere {
            get {
                return ResourceManager.GetString("RightClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动视图 的本地化字符串。
        /// </summary>
        public static string ScrollViewer {
            get {
                return ResourceManager.GetString("ScrollViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索栏 的本地化字符串。
        /// </summary>
        public static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中 的本地化字符串。
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 徽章 的本地化字符串。
        /// </summary>
        public static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示行号 的本地化字符串。
        /// </summary>
        public static string ShowRowNumber {
            get {
                return ResourceManager.GetString("ShowRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滑块 的本地化字符串。
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 的本地化字符串。
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤条 的本地化字符串。
        /// </summary>
        public static string StepBar {
            get {
                return ResourceManager.GetString("StepBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式模板 的本地化字符串。
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子标题 的本地化字符串。
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项卡控件 的本地化字符串。
        /// </summary>
        public static string TabControl {
            get {
                return ResourceManager.GetString("TabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正文 的本地化字符串。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本块 的本地化字符串。
        /// </summary>
        public static string TextBlock {
            get {
                return ResourceManager.GetString("TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间条 的本地化字符串。
        /// </summary>
        public static string TimeBar {
            get {
                return ResourceManager.GetString("TimeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间选择器 的本地化字符串。
        /// </summary>
        public static string TimePicker {
            get {
                return ResourceManager.GetString("TimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是标题 的本地化字符串。
        /// </summary>
        public static string TitleDemoStr1 {
            get {
                return ResourceManager.GetString("TitleDemoStr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此项必填 的本地化字符串。
        /// </summary>
        public static string TitleDemoStr2 {
            get {
                return ResourceManager.GetString("TitleDemoStr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题在左侧 的本地化字符串。
        /// </summary>
        public static string TitleDemoStr3 {
            get {
                return ResourceManager.GetString("TitleDemoStr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换按钮 的本地化字符串。
        /// </summary>
        public static string ToggleButton {
            get {
                return ResourceManager.GetString("ToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具条 的本地化字符串。
        /// </summary>
        public static string ToolBar {
            get {
                return ResourceManager.GetString("ToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 树视图 的本地化字符串。
        /// </summary>
        public static string TreeView {
            get {
                return ResourceManager.GetString("TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瀑布流 的本地化字符串。
        /// </summary>
        public static string WaterfallPanel {
            get {
                return ResourceManager.GetString("WaterfallPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
