{% if theme.cnzz_siteid %}
  <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" : "http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_{{ theme.cnzz_siteid }}'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D{{ theme.cnzz_siteid }}%26online%3D1%26show%3Dline' type='text/javascript'%3E%3C/script%3E"));</script>
{% endif %}
