name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        working-directory: ./build
        run: |
            dotnet new tool-manifest
            dotnet tool install cake.tool --version 4.0.0
            dotnet tool install minver-cli --version 3.0.0
            dotnet cake
