name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@master
      
      - name: Restore Nuget packages
        run: nuget restore src/Net_40/HandyControl_Net_40/HandyControl_Net_40.csproj
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
      
      - name: Build Net_40
        run: msbuild src/Net_40/HandyControl_Net_40/HandyControl_Net_40.csproj -p:Configuration=Release

      - name: Build Net_45
        run: msbuild src/Net_GE45/HandyControl_Net_GE45/HandyControl_Net_GE45.csproj -p:Configuration=Release-Net45

      - name: Build Net_462
        run: msbuild src/Net_GE45/HandyControl_Net_GE45/HandyControl_Net_GE45.csproj -p:Configuration=Release-Net462

      - name: Build Net_47
        run: msbuild src/Net_GE45/HandyControl_Net_GE45/HandyControl_Net_GE45.csproj -p:Configuration=Release-Net47

      - name: Build Net_48
        run: msbuild src/Net_GE45/HandyControl_Net_GE45/HandyControl_Net_GE45.csproj -p:Configuration=Release-Net48

      - name: Build Core_30
        run: dotnet build src/Core_GE30/HandyControl_Core_GE30/HandyControl_Core_GE30.csproj --configuration Release-Core30

      - name: Build Core_31
        run: dotnet build src/Core_GE30/HandyControl_Core_GE30/HandyControl_Core_GE30.csproj --configuration Release-Core31
