on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Build
        shell: pwsh
        run: |
          cd build
          .\build.ps1
